### ISSUE TITLE
我完全按照你的配置环境的步骤去操作的、但是我遇到各种问题，怎么也没法执行。

### ISSUE THREAD

**Issue by Shajiu** [zjunlp/EasyDetect#1]
第一个问题：
File "/root/miniconda3/envs/vlm/lib/python3.10/site-packages/mmdet/__init__.py", line 17, in <module>
    and mmcv_version < digit_version(mmcv_maximum_version)), \
AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

第二个问题：
 raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "output/opencode/EasyDetect/the path of GroundingDINO_SwinT_OGC.py" does not exist

第三个问题跟numpy冲突：
在这里解决https://stackoverflow.com/questions/78636947/a-module-that-was-compiled-using-numpy-1-x-cannot-be-run-in-numpy-2-0-0-as-it-ma

第四个问题在这里解决：
https://github.com/open-mmlab/mmocr/issues/1998

第五个问题：
 import groundingdino.datasets.transforms as T
ModuleNotFoundError: No module named 'groundingdino'

各种问题：

我想请问如下两个文件到底是cd.. 后在EasyDetect/pipeline下执行操作呢？还是跟pipeline平齐目录在EasyDetect下执行？另外可以提供一个类似docak的镜像呢？

**Comment by sunnychenxiwang** [comment]
第一个问题：按照符合区间的版本重新下载即可，"Please install mmcv>=2.0.0rc4, <2.2.0."，如2.0.0
第二个问题：需在config.yaml配置路径即可tool.detect.groundingdino_config
第五个问题：可能是代码包路径出现问题，GroudingDINO和mmocr需装在pipeline文件夹下
第六个问题：需在EasyDetect文件夹下执行操作

**Comment by Shajiu** [comment]
> 第一个问题：按照符合区间的版本重新下载即可，“Please install mmcv>=2.0.0rc4, <2.2.0.”，如2.0.0 第二个问题：需要在config.yaml配置路径即可tool.detect.groundingdino_config 第五个问题：可能是代码包路径出现问题，GroudingDINO和mmocr需安装在pipeline文件夹下 第六个问题：需在EasyDetect文件夹下执行操作

您好感谢您的回复，我按照您的说明配置yaml文件，并且两个插件分别安装在EasyDetect/pipeline/mmocr和EasyDetect/pipeline/GroundingDINO下，然后我在EasyDetect下执行```from pipeline.run_pipeline import *``时遇到如下问题：
 from mmocr.registry import DATASETS
ModuleNotFoundError: No module named 'mmocr'


然后我把“EasyDetect/pipeline/mmocr”复制到EasyDetect下后分别执行from pipeline.run_pipeline import *和from mmocr.registry import DATASETS时都可以，但是又出现“import groundingdino.datasets.transforms as T
ModuleNotFoundError: No module named 'groundingdino.datasets'”问题，然后我又把“cp -a pipeline/GroundingDINO/groundingdino ./”，然后再次执行“from pipeline.run_pipeline import *”时可以，随后执行“pipeline = Pipeline()”时出现如下问题：


raise FileNotFoundError(
FileNotFoundError: Cannot find `configs` directory in /EasyDetect/mmocr!, please check the completeness of the mmocr.

所以我不太能确定以上GroundingDINO和Union14M两个是否下载后在EasyDetect/pipeline下安装呀？

**Comment by sunnychenxiwang** [comment]
![issue](https://github.com/user-attachments/assets/2c039e03-b47f-43e3-8e48-b92ca15042bd)
你好请先确认你的包路径是否和图里的一致

**Comment by Shajiu** [comment]
是一致的，这个是对齐的，然后我现在调试过程中出现了如下问题：
File "EasyDetect/groundingdino/models/GroundingDINO/ms_deform_attn.py", line 53, in forward
    output = _C.ms_deform_attn_forward(
NameError: name '_C' is not defined

**Comment by Shajiu** [comment]
> 是一致的，这是一致的，然后我现在调试过程中出现了如下问题： File "EasyDetect/groundingdino/models/GroundingDINO/ms_deform_attn.py", line 53, inforward output = _C.ms_deform_attn_forward( NameError: name ' _C' 未定义

这个问题我在这里看到https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/15 好像是我环境的问题。

**Comment by Shajiu** [comment]
> > 是一致的，这是一致的，然后我现在调试过程中出现了问题如下： File "EasyDetect/groundingdino/models/GroundingDINO/ms_deform_attn.py", line 53, inforward output = _C.ms_deform_attn_forward( NameError: name ' _C ' 未定义
> 
> 这个问题我在这里看到[IDEA-Research/Grounded-Segment-Anything#15](https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/15)希望是我环境的问题。

cd GroundingDINO
python setup.py build
python setup.py install

!mim install 'mmdet>=3.0.0rc0'
to
!mim install 'mmdet>=3.0.0rc5'


pip uninstall numpy

pip install numpy==1.26.4

**Comment by Shajiu** [comment]
作者您好！～
我现在配置环境太痛苦了，想跟您请教下，您配置是什么版本的呀？GroundingDINO感觉需要的torch版本很低，2.xx以上不支持的样子，而其他LLM必须需要2.xx以上的，您能提供全部的版本号么？
cunda：
torch                             
torchvision                    
tornado 
transformers


出现的问题1:
UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")


问题2:
File "EasyDetect/groundingdino/models/GroundingDINO/ms_deform_attn.py", line 53, in forward
    output = _C.ms_deform_attn_forward(
NameError: name '_C' is not defined

**Comment by sunnychenxiwang** [comment]
你好 我刚刚重新上传了我的requirement.txt 上面有对应的版本号

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by Shajiu** [comment]
> 你好 我刚刚重新上传了我的requirement.txt 上面有对应的版本号

您好，我现在按照您的新配置环境发现如下问题：
INFO: pip is still looking at multiple versions of requests to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install codecov and urllib3==2.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==2.1.0
    requests 2.28.2 depends on urllib3<1.27 and >=1.21.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by sunnychenxiwang** [comment]
你好，我猜测你的requests版本没有和我们的requirements.txt上提供的版本一致，我们的版本是requests==2.31.0 以及 urllib3==2.1.0

**Comment by Shajiu** [comment]
> 你好，我猜测你的requests版本没有和我们的requirements.txt上提供的版本一致，我们的版本是requests==2.31.0 以及 urllib3==2.1.0

您好呀～！ 我从python3.8、3.9、3.10、3.11、3.12都尝试还是不行，出现各种问题；比如“ModuleNotFoundError: No module named 'mmcv._ext'”，比如“ERROR: No matching distribution found for contourpy==1.2.1”，比如“from torch._C import *  # noqa: F403”，方便加您微信  请教您么？18810979033，万分感谢～

**Comment by le-liuzhe** [comment]
> 您好呀～！ 我从python3.8、3.9、3.10、3.11、3.12都尝试还是不行，出现各种问题；比如“ModuleNotFoundError: No module named 'mmcv._ext'”，比如“ERROR: No matching distribution found for contourpy==1.2.1”，比如“from torch._C import * # noqa: F403”，方便加您微信 请教您么？18810979033，万分感谢～

请问你的问题解决了吗，方便的话可以请您告知一下解决方法吗

**Comment by sunnychenxiwang** [comment]
> > 您好呀～！ 我从python3.8、3.9、3.10、3.11、3.12都尝试还是不行，出现各种问题；比如“ModuleNotFoundError: No module named 'mmcv._ext'”，比如“ERROR: No matching distribution found for contourpy==1.2.1”，比如“from torch._C import * # noqa: F403”，方便加您微信 请教您么？18810979033，万分感谢～
> 
> 请问你的问题解决了吗，方便的话可以请您告知一下解决方法吗

你好 （1）环境可以参考我们上传的requirements.txt （2）来自于其他仓库的issue，如from torch._C import * 可参考原始仓库的回复如：https://github.com/IDEA-Research/GroundingDINO/issues/8

**Comment by zxlzr** [comment]
> > 您好呀～！ 我从python3.8、3.9、3.10、3.11、3.12都尝试还是不行，出现各种问题；比如“ModuleNotFoundError: No module named 'mmcv._ext'”，比如“ERROR: No matching distribution found for contourpy==1.2.1”，比如“from torch._C import * # noqa: F403”，方便加您微信 请教您么？18810979033，万分感谢～
> 
> 请问你的问题解决了吗，方便的话可以请您告知一下解决方法吗
请问你的问题解决了吗

**Comment by YUEFANG0211** [comment]
> > 你好，我猜测你的requests版本没有和我们的requirements.txt上提供的版本一致，我们的版本是requests==2.31.0 以及 urllib3==2.1.0
> 
> 您好呀～！ 我从python3.8、3.9、3.10、3.11、3.12都尝试还是不行，出现各种问题；比如“ModuleNotFoundError: No module named 'mmcv._ext'”，比如“ERROR: No matching distribution found for contourpy==1.2.1”，比如“from torch._C import * # noqa: F403”，方便加您微信 请教您么？18810979033，万分感谢～

您好，抱歉打扰您了！请问您是在cuda124上安装的pytorch2.0.1吗？我关注到pytoch2.0.1只支持cuda118和117，请问您是如何解决这个问题的呢？感谢拨冗回复！
